config/routes.rb
Rails.application.routes.draw do
  resources :sales
  
  root 'sales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales_all = Sale.group_by_month(:sale_date, last: 12).sum(:price)
    @sales_amount_month = Sale.group_by_month(:sale_date, last: 12).sum(:amount)
    @sales_average = Sale.group_by_month(:sale_date, last: 12).average(:amount)
        
    @sales_amount12 = Sale.where('sale_date > ?', 1.year.ago).group(:origin).count

    @sales_amount6 = Sale.where('sale_date > ?', 6.month.ago).group(:origin).count

    @sales_amount3 = Sale.where('sale_date > ?', 3.month.ago).group(:origin).count

    @sales_amount1 = Sale.where('sale_date > ?', 1.month.ago).group(:origin).count

    @sales_blend_coffee12 = Sale.where('sale_date > ?', 1.year.ago).group(:blend_coffee).count 
        
    @sales_blend_coffee6 = Sale.where('sale_date > ?', 6.month.ago).group(:blend_coffee).count  

    @sales_blend_coffee3 = Sale.where('sale_date > ?', 3.month.ago).group(:blend_coffee).count 

    @sales_blend_coffee1 = Sale.where('sale_date > ?', 1.month.ago).group(:blend_coffee).count
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:price, :blend_coffe, :origin, :sale_date, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--CSS de Bootstrap v 4.6-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :blend_coffe %>
    <%= form.text_field :blend_coffe %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :sale_date %>
    <%= form.date_select :sale_date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<br>
<div class="container">
<div class="row">
<div class="col-6">
<h3>Monthly sales</h3>
<%= column_chart @sales_all %>
</div>
<div class="col-6">
<h3>Monthly sales amount</h3>
<%= column_chart @sales_amount_month %>
</div>
<h3>Average monthly sales</h3>
<%= column_chart @sales_average, colors: ["#8E44AD"] %>
</div>
<br>
<br>
<h3>Number of sales according to the origin of the coffee</h3>
<br>
<h4>Last 12 months</h4>
<%= pie_chart @sales_amount12, width: "1100px", height: "800px" %>
<h4>Last 6 months</h4>
<%= pie_chart @sales_amount6, width: "1100px", height: "700px" %>
<h4>Last 3 months</h4>
<%= pie_chart @sales_amount3, width: "1100px", height: "600px" %>
<h4>Last month</h4>
<%= pie_chart @sales_amount1, width: "1100px", height: "500px" %>
<br>
<h3>Sales quantity according to the name of the coffee blend</h3>
<br>
<h4>Last 12 months</h4>
<%= pie_chart @sales_blend_coffee12, width: "1100px", height: "1300px" %>
<h4>Last 6 months</h4>
<%= pie_chart @sales_blend_coffee6, width: "1100px", height: "900px" %>
<h4>Last 3 months</h4>
<%= pie_chart @sales_blend_coffee3, width: "1100px", height: "620px" %>
<h4>Last month</h4>
<%= pie_chart @sales_blend_coffee1, width: "1100px", height: "480px" %>
</div>


<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @sale.price %>
</p>

<p>
  <strong>Blend coffe:</strong>
  <%= @sale.blend_coffe %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @sale.origin %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @sale.sale_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @sale.amount %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>